# Nome do workflow que aparecerá na aba "Actions" do seu repositório
name: Construir e Publicar Imagem Odoo no GHCR

# Define o gatilho (trigger) para iniciar o workflow.
on:
  push:
    branches:
      - "main"

# Define os trabalhos (jobs) a serem executados.
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
 
      - name: "Setup Build Version"
        run: |
          echo "BUILD_VERSION=14.0.${{ github.run_number }}" >> $GITHUB_ENV
          echo "Build version: 14.0.${{ github.run_number }}"
      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Build and push Docker image to Github Registry
        uses: docker/build-push-action@v5
        with:
          context: ./odoo/
          build-args: |
            ODOO_VERSION=${{ github.ref_name }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/doodba-clean:${{ env.BUILD_VERSION }}
 
